# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AirClock
email: airclock@al4.co.nz
description: > # this means to ignore newlines until "baseurl:"
  A time-shifting clock to help you combat jet-lag
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://al4.github.io/AirClock" # the base hostname & protocol for your site
twitter_username: al4
github_username: al4

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
